# -*- coding: utf-8 -*-
"""Lonelyinteger

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1REWcElho4ARk1gP5vMmh2axT5v8CVGoK
"""

#Lonely integer 
#Read a as input from user 
#a = [1,1,2,2,3,3,4]
b = {}
for i in a:
  b[i] = 0
for i in a:  
  b[i] += 1
for i in b:
  if b[i] == 1:
    print(i)